Update requirements.txt (#33)
Updating julicall version due to this error during pypi publication:
```
ERROR: Unsatisfiable requirements detected for package PythonCall [6099a3de]:
 PythonCall [6099a3de] log:
 ├─possible versions are: 0.1.0-0.9.23 or uninstalled
 ├─restricted to versions 0.9.22 by BraketSimulator [76d27892], leaving only versions: 0.9.22 or uninstalled
 │ └─BraketSimulator [76d27892] log:
 │   ├─possible versions are: 0.0.3 or uninstalled
 │   └─BraketSimulator [76d27892] is fixed to version 0.0.3
 └─restricted to versions 0.9.20 by an explicit requirement — no versions left
```